# hypr/modules/autostart.conf

exec-once = ~/.dotfiles/hypr/.config/hypr/rand_wallpaper.sh && hyprpaper
exec-once = waybar
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

