# hypr/modules/layout.conf

general {
    layout = master
}

dwindle {
    force_split = 2
    preserve_split = true
    smart_split = false 
}

master {
    allow_small_split = true
    mfact = 0.6
    new_status = master 
}
