# hypr/modules/window.conf

windowrule {
    name = float-by-class

    match:class = (org.kde.polkit-kde-authentication-agent-1|xdg-desktop-portal-gtk|nm-connection-editor|blueman-manager|engrampa)

    float = on
    center = on
    persistent_size = on
}
