"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

format = "$directory$git_branch$git_status$nodejs$rust$golang$php$character"

[directory]
format = "[$path](bold #b8bb26) "
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = ""
format = "[$symbol $branch](#83a598) "

[git_status]
format = "($ahead_behind$staged$modified$untracked$deleted$conflicted)"
ahead = "[⇡$count ](#8ec07c)"
behind = "[⇣$count ](#8ec07c)"
diverged = "[⇕ ](#fabd2f)"
staged = "[+$count ](#b8bb26)"
modified = "[~$count ](#fabd2f)"
untracked = "[?$count ](#83a598)"
deleted = "[-$count ](#fb4934)"
conflicted = "[!$count ](#fb4934)"

[nodejs]
symbol = ""
format = "[ $version](#b8bb26) "

[rust]
symbol = ""
format = "[ $version](#d3869b) "

[golang]
symbol = ""
format = "[ $version](#83a598) "

[php]
symbol = ""
format = "[ $version](#d3869b) "

[character]
success_symbol = "[❯](bold #b8bb26)"
error_symbol = "[❯](bold #fb4934)"
vimcmd_symbol = "[❮](bold #83a598)"
