wallpaper {
    monitor = HDMI-A-1
    path = /home/actias/.dotfiles/wallpapers/wallpaper3.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = /home/actias/.dotfiles/wallpapers/wallpaper3.png
    fit_mode = cover
}

splash = false
